**Fonte dos dados :**

https://platform.stratascratch.com/data-projects/terrorism-hotspots

**Atribuição**

Imagine que você é um analista de segurança ou defesa. Analisar os dados e tirar conclusões sobre a distribuição e a natureza dos incidentes terroristas registados em todo o mundo. Na sua análise, inclua mapas que visualizem a localização de diferentes incidentes. Sua análise também pode fornecer respostas às seguintes perguntas:

- Como o número de atividades terroristas mudou ao longo dos anos? Existem certas regiões onde esta tendência é diferente das médias globais?
- O número de incidentes e o número de vítimas estão correlacionados? Você consegue detectar alguma irregularidade ou valores discrepantes?
- Quais são os métodos de ataque mais comuns? Difere em várias regiões ou no tempo?
- Trace os locais dos ataques em um mapa para visualizar sua distribuição regional;

Você também está livre para explorar mais os dados e extrair insights adicionais além das perguntas acima.

**Descrição de dados.**

O arquivo compactado fornecido globalterrorismdb_0718dist.tar.bz2é um extrato do Global Terrorism Database (GTD) - um banco de dados de código aberto que inclui informações sobre ataques terroristas em todo o mundo de 1970 a 2017. O GTD inclui dados sistemáticos sobre incidentes terroristas nacionais e internacionais que ocorreram durante este período e agora inclui mais de 180.000 ataques. O banco de dados é mantido por pesquisadores do Consórcio Nacional para o Estudo do Terrorismo e Respostas ao Terrorismo (START), com sede na Universidade de Maryland.

Como o número de variáveis ​​e instâncias é muito grande, para este projeto fique à vontade para selecionar um subconjunto de colunas ou um período de tempo específico.

**Explicação das colunas selecionadas:**

- success- Sucesso de um ataque terrorista
- suicide- 1 = "Sim" O incidente foi um ataque suicida. 0 = "Não" Não há  
  indicação de que o incidente tenha sido suicídio
- attacktype1- O método geral de ataque
- attacktype1_txt- O método geral de ataque e ampla classe de táticas
  utilizadas.
- targtype1_txt- O tipo geral de alvo/vítima
- targsubtype1_txt- A categoria alvo mais específica
- target1- A pessoa, edifício ou instalação específica que foi visada e/ou
  vitimada
- natlty1_txt- A nacionalidade do alvo que foi atacado
- gname- O nome do grupo que executou o ataque
- gsubname- Detalhes adicionais sobre o grupo que realizou o ataque como frações
- nperps- O número total de terroristas que participaram no incidente
- weaptype1_txt- Tipo geral de arma utilizada no incidente
- weapsubtype1_txt- Valor mais específico para a maioria dos tipos de armas
- nkill- O número total de mortes confirmadas para o incidente
- nkillus- O número de cidadãos dos EUA que morreram como resultado do incidente

In [ ]:
# @title Bibliotecas

import pandas as pd

In [ ]:
# @title Criação Data Frame

df = pd.read_csv("globalterrorismdb_0718dist.tar.bz2", compression="bz2")

<ipython-input-4-98f7fc22be85>:3: DtypeWarning: Columns (5,7,32,34,62,63,64,77,80,91,93,95,97,115,116,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("globalterrorismdb_0718dist.tar.bz2", compression="bz2")

In [ ]:
df.head(5)

,Unnamed: 0,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [ ]:
# @title Selecionando colunas de interesse

df_select = df[['country_txt','iyear','success','suicide','attacktype1','attacktype1_txt','targtype1_txt','targsubtype1_txt','target1','natlty1_txt','gname','gsubname','nperps','weaptype1_txt','weapsubtype1_txt','nkill','nkillus']]

In [ ]:
df_select.head(5)

,country_txt,iyear,success,suicide,attacktype1,attacktype1_txt,targtype1_txt,targsubtype1_txt,target1,natlty1_txt,gname,gsubname,nperps,weaptype1_txt,weapsubtype1_txt,nkill,nkillus
0,Dominican Republic,1970,1,0,1,Assassination,Private Citizens & Property,Named Civilian,Julio Guzman,Dominican Republic,MANO-D,NaN,NaN,Unknown,NaN,1.0,NaN
1,Mexico,1970,1,0,6,Hostage Taking (Kidnapping),Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...","Nadine Chaval, daughter",Belgium,23rd of September Communist League,NaN,7.0,Unknown,NaN,0.0,NaN
2,Philippines,1970,1,0,1,Assassination,Journalists & Media,Radio Journalist/Staff/Facility,Employee,United States,Unknown,NaN,NaN,Unknown,NaN,1.0,NaN
3,Greece,1970,1,0,3,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,U.S. Embassy,United States,Unknown,NaN,NaN,Explosives,Unknown Explosive Type,NaN,NaN
4,Japan,1970,1,0,7,Facility/Infrastructure Attack,Government (Diplomatic),Embassy/Consulate,U.S. Consulate,United States,Unknown,NaN,NaN,Incendiary,NaN,NaN,NaN

## **Contagem de Vítimas por ano**

In [ ]:
# Contando as vitimas por ano
incident_victims = df_select.groupby('iyear')['nkill'].sum().astype(int)

In [ ]:
incident_victims.head(5)

iyear
1970    174
1971    173
1972    566
1973    370
1974    539
Name: nkill, dtype: int64

In [ ]:
# Salvando em .csv

incident_victims.to_csv('incident_victims.csv')

## **Casos por países | Por ano | Casos que obtiveram sucesso | Casos apenas nos EUA**

In [ ]:
# @title Casos por paises e selecionando o top 20
case_per_country = df_select['country_txt'].value_counts()
top20_country = case_per_country.head(20)
top20_country

country_txt
Iraq              24636
Pakistan          14368
Afghanistan       12731
India             11960
Colombia           8306
Philippines        6908
Peru               6096
El Salvador        5320
United Kingdom     5235
Turkey             4292
Somalia            4142
Nigeria            3907
Thailand           3849
Yemen              3347
Spain              3249
Sri Lanka          3022
United States      2836
Algeria            2743
France             2693
Egypt              2479
Name: count, dtype: int64

In [ ]:
# Salvando .csv
top20_country.to_csv('top20_country.csv')

In [ ]:
# @title Casos que obtiveram sucesso
cases_year_success = df_select.groupby(['iyear', 'success']).size().sort_index()
cases_year_success.head(5)

iyear  success
1970   0            102
       1            549
1971   0             51
       1            420
1972   0            116
                  ...
2015   1          12676
2016   0           2612
       1          10975
2017   0           2248
       1           8652
Length: 94, dtype: int64

In [ ]:
# Salvando .csv
cases_year_success.to_csv('cases_year_success.csv')

In [ ]:
# @title Casos por ano
cases_year = df_select['iyear'].value_counts().sort_index()
cases_year.tail(5)

iyear
2013    12036
2014    16903
2015    14965
2016    13587
2017    10900
Name: count, dtype: int64

In [ ]:
# Salvando .csv
cases_year.to_csv('cases_year.csv')

In [ ]:
# @title Casos USA
# Filtrar para incluir apenas 'United States'
df_usa = df_select[df_select['country_txt'] == 'United States']

# Contar quantos ataques aconteceram por cada ano
case_usa = df_usa['iyear'].value_counts().sort_index()
case_usa.head(5)

iyear
1970    468
1971    247
1972     68
1973     58
1974     94
Name: count, dtype: int64

In [ ]:
# Salvando .csv
case_usa.to_csv('case_usa.csv')

## **Tipos de atentados**

In [ ]:
# @title Mapeamento de países para regiões
country_to_region = {
    'Afghanistan': 'Asia', 'Albania': 'Europe', 'Algeria': 'Africa', 'Andorra': 'Europe', 'Angola': 'Africa',
    'Antigua and Barbuda': 'North America', 'Argentina': 'South America', 'Armenia': 'Asia', 'Australia': 'Oceania',
    'Austria': 'Europe', 'Azerbaijan': 'Asia', 'Bahamas': 'North America', 'Bahrain': 'Asia', 'Bangladesh': 'Asia',
    'Barbados': 'North America', 'Belarus': 'Europe', 'Belgium': 'Europe', 'Belize': 'North America', 'Benin': 'Africa',
    'Bhutan': 'Asia', 'Bolivia': 'South America', 'Bosnia and Herzegovina': 'Europe', 'Botswana': 'Africa', 'Brazil': 'South America',
    'Brunei': 'Asia', 'Bulgaria': 'Europe', 'Burkina Faso': 'Africa', 'Burundi': 'Africa', 'Cabo Verde': 'Africa',
    'Cambodia': 'Asia', 'Cameroon': 'Africa', 'Canada': 'North America', 'Central African Republic': 'Africa', 'Chad': 'Africa',
    'Chile': 'South America', 'China': 'Asia', 'Colombia': 'South America', 'Comoros': 'Africa', 'Congo (Congo-Brazzaville)': 'Africa',
    'Costa Rica': 'North America', 'Croatia': 'Europe', 'Cuba': 'North America', 'Cyprus': 'Europe', 'Czechia (Czech Republic)': 'Europe',
    'Denmark': 'Europe', 'Djibouti': 'Africa', 'Dominica': 'North America', 'Dominican Republic': 'North America', 'Ecuador': 'South America',
    'Egypt': 'Africa', 'El Salvador': 'North America', 'Equatorial Guinea': 'Africa', 'Eritrea': 'Africa', 'Estonia': 'Europe',
    'Eswatini (fmr. "Swaziland")': 'Africa', 'Ethiopia': 'Africa', 'Fiji': 'Oceania', 'Finland': 'Europe', 'France': 'Europe',
    'Gabon': 'Africa', 'Gambia': 'Africa', 'Georgia': 'Asia', 'Germany': 'Europe', 'Ghana': 'Africa',
    'Greece': 'Europe', 'Grenada': 'North America', 'Guatemala': 'North America', 'Guinea': 'Africa', 'Guinea-Bissau': 'Africa',
    'Guyana': 'South America', 'Haiti': 'North America', 'Honduras': 'North America', 'Hungary': 'Europe', 'Iceland': 'Europe',
    'India': 'Asia', 'Indonesia': 'Asia', 'Iran': 'Asia', 'Iraq': 'Asia', 'Ireland': 'Europe',
    'Israel': 'Asia', 'Italy': 'Europe', 'Jamaica': 'North America', 'Japan': 'Asia', 'Jordan': 'Asia',
    'Kazakhstan': 'Asia', 'Kenya': 'Africa', 'Kiribati': 'Oceania', 'Kuwait': 'Asia', 'Kyrgyzstan': 'Asia',
    'Laos': 'Asia', 'Latvia': 'Europe', 'Lebanon': 'Asia', 'Lesotho': 'Africa', 'Liberia': 'Africa',
    'Libya': 'Africa', 'Liechtenstein': 'Europe', 'Lithuania': 'Europe', 'Luxembourg': 'Europe', 'Madagascar': 'Africa',
    'Malawi': 'Africa', 'Malaysia': 'Asia', 'Maldives': 'Asia', 'Mali': 'Africa', 'Malta': 'Europe',
    'Marshall Islands': 'Oceania', 'Mauritania': 'Africa', 'Mauritius': 'Africa', 'Mexico': 'North America', 'Micronesia': 'Oceania',
    'Moldova': 'Europe', 'Monaco': 'Europe', 'Mongolia': 'Asia', 'Montenegro': 'Europe', 'Morocco': 'Africa',
    'Mozambique': 'Africa', 'Myanmar (formerly Burma)': 'Asia', 'Namibia': 'Africa', 'Nauru': 'Oceania', 'Nepal': 'Asia',
    'Netherlands': 'Europe', 'New Zealand': 'Oceania', 'Nicaragua': 'North America', 'Niger': 'Africa', 'Nigeria': 'Africa',
    'North Korea': 'Asia', 'North Macedonia': 'Europe', 'Norway': 'Europe', 'Oman': 'Asia', 'Pakistan': 'Asia',
    'Palau': 'Oceania', 'Palestine State': 'Asia', 'Panama': 'North America', 'Papua New Guinea': 'Oceania', 'Paraguay': 'South America',
    'Peru': 'South America', 'Philippines': 'Asia', 'Poland': 'Europe', 'Portugal': 'Europe', 'Qatar': 'Asia',
    'Romania': 'Europe', 'Russia': 'Europe', 'Rwanda': 'Africa', 'Saint Kitts and Nevis': 'North America', 'Saint Lucia': 'North America',
    'Saint Vincent and the Grenadines': 'North America', 'Samoa': 'Oceania', 'San Marino': 'Europe', 'Sao Tome and Principe': 'Africa', 'Saudi Arabia': 'Asia',
    'Senegal': 'Africa', 'Serbia': 'Europe', 'Seychelles': 'Africa', 'Sierra Leone': 'Africa', 'Singapore': 'Asia',
    'Slovakia': 'Europe', 'Slovenia': 'Europe', 'Solomon Islands': 'Oceania', 'Somalia': 'Africa', 'South Africa': 'Africa',
    'South Korea': 'Asia', 'South Sudan': 'Africa', 'Spain': 'Europe', 'Sri Lanka': 'Asia', 'Sudan': 'Africa',
    'Suriname': 'South America', 'Sweden': 'Europe', 'Switzerland': 'Europe', 'Syria': 'Asia', 'Tajikistan': 'Asia',
    'Tanzania': 'Africa', 'Thailand': 'Asia', 'Timor-Leste': 'Asia', 'Togo': 'Africa', 'Tonga': 'Oceania',
    'Trinidad and Tobago': 'North America', 'Tunisia': 'Africa', 'Turkey': 'Asia', 'Turkmenistan': 'Asia', 'Tuvalu': 'Oceania',
    'Uganda': 'Africa', 'Ukraine': 'Europe', 'United Arab Emirates': 'Asia', 'United Kingdom': 'Europe', 'United States': 'North America',
    'Uruguay': 'South America', 'Uzbekistan': 'Asia', 'Vanuatu': 'Oceania', 'Venezuela': 'South America', 'Vietnam': 'Asia',
    'Yemen': 'Asia', 'Zambia': 'Africa', 'Zimbabwe': 'Africa'
}

In [ ]:
# Criando uma copia do dataframe base
df_2 = df_select

In [ ]:
# Adicionar uma coluna de região ao DataFrame
df_2['region'] = df_2['country_txt'].map(country_to_region)
df_2

<ipython-input-11-ef8febfbc951>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['region'] = df_2['country_txt'].map(country_to_region)

,country_txt,iyear,success,suicide,attacktype1,attacktype1_txt,targtype1_txt,targsubtype1_txt,target1,natlty1_txt,gname,gsubname,nperps,weaptype1_txt,weapsubtype1_txt,nkill,nkillus,region
0,Dominican Republic,1970,1,0,1,Assassinato,Private Citizens & Property,Named Civilian,Julio Guzman,Dominican Republic,MANO-D,NaN,NaN,Unknown,NaN,1.0,NaN,North America
1,Mexico,1970,1,0,6,Sequestro,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...","Nadine Chaval, daughter",Belgium,23rd of September Communist League,NaN,7.0,Unknown,NaN,0.0,NaN,North America
2,Philippines,1970,1,0,1,Assassinato,Journalists & Media,Radio Journalist/Staff/Facility,Employee,United States,Unknown,NaN,NaN,Unknown,NaN,1.0,NaN,Asia
3,Greece,1970,1,0,3,Bombardeio/Explosão,Government (Diplomatic),Embassy/Consulate,U.S. Embassy,United States,Unknown,NaN,NaN,Explosives,Unknown Explosive Type,NaN,NaN,Europe
4,Japan,1970,1,0,7,Ataque a Instalações/Infra,Government (Diplomatic),Embassy/Consulate,U.S. Consulate,United States,Unknown,NaN,NaN,Incendiary,NaN,NaN,NaN,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,Somalia,2017,1,0,2,Assalto Armado,Military,Military Checkpoint,Checkpoint,Somalia,Al-Shabaab,NaN,-99.0,Firearms,Unknown Gun Type,1.0,0.0,Africa
181687,Syria,2017,1,0,3,Bombardeio/Explosão,Military,Military Barracks/Base/Headquarters/Checkpost,Hmeymim Air Base,Russia,Muslim extremists,NaN,-99.0,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",2.0,0.0,Asia
181688,Philippines,2017,1,0,7,Ataque a Instalações/Infra,Private Citizens & Property,House/Apartment/Residence,Houses,Philippines,Bangsamoro Islamic Freedom Movement (BIFM),NaN,-99.0,Incendiary,Arson/Fire,0.0,0.0,Asia
181689,India,2017,0,0,3,Bombardeio/Explosão,Government (General),Government Building/Facility/Office,Office,India,Unknown,NaN,-99.0,Explosives,Grenade,0.0,0.0,Asia
181690,Philippines,2017,0,0,3,Bombardeio/Explosão,Unknown,NaN,Unknown,Philippines,Unknown,NaN,-99.0,Explosives,Unknown Explosive Type,0.0,0.0,Asia

In [ ]:
translation_dict = {
    'Bombing/Explosion': 'Bombardeio/Explosão',
    'Armed Assault': 'Assalto Armado',
    'Assassination': 'Assassinato',
    'Hostage Taking (Kidnapping)': 'Sequestro',
    'Facility/Infrastructure Attack': 'Ataque a Instalações/Infra',
    'Unknown': 'Desconhecido',
    'Unarmed Assault': 'Assalto Desarmado',
    'Hostage Taking (Barricade Incident)': 'Incidente com Barricada',
    'Hijacking': 'Sequestro de Veículo'
}

# Renomeia os valores na coluna 'attacktype1_txt'
df_2['attacktype1_txt'] = df_2['attacktype1_txt'].replace(translation_dict)

<ipython-input-8-4704afc6d372>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['attacktype1_txt'] = df_2['attacktype1_txt'].replace(translation_dict)

In [ ]:
# Historico de atentados por regiao

atk_north_america = df_2[df_2['region'] == 'North America'] .groupby('iyear')
case_na = atk_north_america['iyear'].value_counts().sort_index()
atk_south_america = df_2[df_2['region'] == 'South America'] .groupby('iyear')
case_sa = atk_south_america['iyear'].value_counts().sort_index()
atk_europe = df_2[df_2['region'] == 'Europe'] .groupby('iyear')
case_eu = atk_europe['iyear'].value_counts().sort_index()
atk_asia = df_2[df_2['region'] == 'Asia'] .groupby('iyear')
case_asia = atk_asia['iyear'].value_counts().sort_index()
atk_africa = df_2[df_2['region'] == 'Africa'] .groupby('iyear')
case_africa = atk_africa['iyear'].value_counts().sort_index()

# Salvando .csv
case_na.to_csv('case_na.csv')
case_sa.to_csv('case_sa.csv')
case_eu.to_csv('case_eu.csv')
case_asia.to_csv('case_asia.csv')
case_africa.to_csv('case_africa.csv')

In [ ]:
# @title Contagem por tipos de ataque
df_typeattack_count = df_select['attacktype1_txt'].value_counts()
df_typeattack_count

attacktype1_txt
Bombardeio/Explosão           88255
Assalto Armado                42669
Assassinato                   19312
Sequestro                     11158
Ataque a Instalações/Infra    10356
Desconhecido                   7276
Assalto Desarmado              1015
Incidente com Barricada         991
Sequestro de Veículo            659
Name: count, dtype: int64

In [ ]:
# Salvando .csv
df_typeattack_count.to_csv('typeattack_count.csv')

In [ ]:
# @title Tipos de ataques por região
types_region = df_select.groupby(['region','attacktype1_txt']).size().sort_index()
types_region.head(10)

region  attacktype1_txt
Africa  Assalto Armado                 7764
        Assalto Desarmado                93
        Assassinato                    2492
        Ataque a Instalações/Infra      968
        Bombardeio/Explosão            8739
        Desconhecido                   1530
        Incidente com Barricada         107
        Sequestro                      2253
        Sequestro de Veículo            184
Asia    Assalto Armado                21752
dtype: int64

In [ ]:
# Separando por região
typ_atk_africa = types_region['Africa'].idxmax()
typ_atk_asia = types_region['Asia'].idxmax()
typ_atk_europe = types_region['Europe'].idxmax()
typ_atk_north_america = types_region['North America'].idxmax()
typ_atk_south_america = types_region['South America'].idxmax()

In [ ]:
print(f'Ataques mais comum: Africa/{typ_atk_africa} | Asia/{typ_atk_asia} | Europe/{typ_atk_europe} | North America/{typ_atk_north_america} | South America/{typ_atk_south_america}')

Ataques mais comum: Africa/Bombardeio/Explosão | Asia/Bombardeio/Explosão | Europe/Bombardeio/Explosão | North America/Assalto Armado | South America/Bombardeio/Explosão

In [ ]:
# @title Tipos de ataques por ano

df_typeattack_year = df_select.groupby(['attacktype1_txt','iyear']).size().sort_index()
df_typeattack_year

attacktype1_txt       iyear
Assalto Armado        1970     61
                      1971     44
                      1972     63
                      1973     62
                      1974     46
                               ..
Sequestro de Veículo  2013     17
                      2014     49
                      2015     38
                      2016     43
                      2017     58
Length: 416, dtype: int64

In [ ]:
# Salvando .csv
df_typeattack_year.to_csv('type_atk_year.csv')

- **Análise Geral:**

Desde 1970, foram registrados mais de 170 mil ataques terroristas em todo o mundo, afetando países de todos os continentes.
Os países mais afetados são Iraque, Paquistão, Afeganistão, Índia e Colômbia, que juntos representam uma parcela significativa dos ataques registrados.

- **Análise Temporal:**

O número de ataques teve um aumento significativo a partir da década de 2000, atingindo o pico em 2014, e desde então tem mostrado uma tendência de queda.
Este período de aumento pode ser atribuído a eventos geopolíticos e conflitos regionais, como a guerra no Iraque e no Afeganistão.

- **Análise de Vítimas:**

A contagem total de vítimas fatais de ataques terroristas mostra um aumento gradual ao longo das décadas, com picos em anos de grande atividade terrorista.
A letalidade dos ataques, medida pela porcentagem de ataques que resultaram em vítimas fatais, variou ao longo dos anos, refletindo a eficácia das medidas de segurança e prevenção.

- **Tipos de Ataques:**

Os ataques mais comuns são bombardeios/explosões, seguidos por assaltos armados e assassinatos, indicando a diversidade de táticas utilizadas pelos grupos terroristas.
A análise temporal dos tipos de ataques mostra mudanças nas táticas preferidas, com alguns tipos de ataques se tornando mais comuns em determinados períodos.

- **Análise por Região**:

A distribuição dos tipos de ataques por região revela padrões interessantes, como a predominância de bombardeios/explosões na África e na Ásia, e de assaltos armados na América do Norte.
Esses padrões podem refletir diferenças na natureza dos conflitos e nas estratégias dos grupos terroristas em diferentes regiões.

- **Ataques nos Estados Unidos:**

Nos Estados Unidos, os ataques terroristas têm sido menos frequentes do que em outras regiões, com picos em anos específicos, como em 2001, devido aos ataques de 11 de setembro.

- **Conclusão:**

A análise do Global Terrorism Database fornece insights valiosos sobre a natureza e a evolução do terrorismo ao longo das décadas, destacando a importância da vigilância e da cooperação internacional na prevenção e combate ao terrorismo.
A compreensão desses padrões pode ajudar na formulação de políticas e estratégias mais eficazes para enfrentar essa ameaça global.